<?php include("header.inc.php");?>

<body>
  <?php
  include("cap.inc.php");
  //echo Functions::createHeader();

  //<img src="App/View/Templates/img/slide1.jpg"/>
$slides="
<li style=\"background-image: url('App/View/Templates/img/slide1.jpg'); width: 100%; float: left; margin-right: -100%; display: none; background-position: 50% 0px; background-repeat: no-repeat no-repeat;\">
      <div class=\"hold\" style='position:relative; overflow:hidden; z-index:2000'>

      <a href=\"\">THE #CRUYFFTURN
      </br>SPEED CHALLENGE
      </br>HEATS UP
      </a>
      </div>
      </li>

      <li style=\"background-image: url('App/View/Templates/img/slide2.jpg'); width: 100%; float: left; margin-right: -100%; display: none; background-position: 50% 0px; background-repeat: no-repeat no-repeat;\">
      <div class=\"hold\" style='position:relative; overflow:hidden; z-index:2000'>

      <a href=\"\">THE #CRUYFFTURN
      </br>SPEED CHALLENGE
      </br>HEATS UP
      </a>
      </div>
      </li>
  ";
  ?>



  <div class="flexslider">
  <ul class="slides">


      <?php echo $slides?>


 </ul>
  </div>





  <p class="home_tip">WELCOME TO TRUSOX</p>
  <div id="container" role="main">
        <div class="item item_home" style="background-image: url('App/View/Templates/img/bg_box_home.jpg');" >
           <div class="text_box">
               <div class="title_box">
               Helen Rose
               <br/>England Striker
               </div>
               <div  class="subtitle_box">
               Lorem Ipsum Dolores Sumitas Simitus
               <br/>Afranio Voluptat Sedio Proin Commodo Aesopio Volutpat Blandit
               </div>
               <div  class="link_box">
                   >
               </div>
           </div>
           <span class="overlay"></span>
        </div>

      <div class="item item_home" style="background-image: url('App/View/Templates/img/bg_box_home.jpg');" >
          <div class="text_box">
              <div class="title_box">
                  Helen Rose
                  <br/>England Striker
              </div>
              <div  class="subtitle_box">
                  Lorem Ipsum Dolores Sumitas Simitus
                  <br/>Afranio Voluptat Sedio Proin Commodo Aesopio Volutpat Blandit
              </div>
              <div  class="link_box">
                  >
              </div>
          </div>
          <span class="overlay"></span>
      </div>

      <div class="item item_home" style="background-image: url('App/View/Templates/img/bg_box_home.jpg');" >
          <div class="text_box">
              <div class="title_box">
                  Helen Rose
                  <br/>England Striker
              </div>
              <div  class="subtitle_box">
                  Lorem Ipsum Dolores Sumitas Simitus
                  <br/>Afranio Voluptat Sedio Proin Commodo Aesopio Volutpat Blandit
              </div>
              <div  class="link_box">
                  >
              </div>
          </div>
          <span class="overlay"></span>
      </div>
      <div class="item item_home" style="background-image: url('App/View/Templates/img/bg_box_home.jpg');" >
          <div class="text_box">
              <div class="title_box">
                  Helen Rose
                  <br/>England Striker
              </div>
              <div  class="subtitle_box">
                  Lorem Ipsum Dolores Sumitas Simitus
                  <br/>Afranio Voluptat Sedio Proin Commodo Aesopio Volutpat Blandit
              </div>
              <div  class="link_box">
                  >
              </div>
          </div>
          <span class="overlay"></span>
      </div>
      <div class="item item_home" style="background-image: url('App/View/Templates/img/bg_box_home.jpg');" >
          <div class="text_box">
              <div class="title_box">
                  Helen Rose
                  <br/>England Striker
              </div>
              <div  class="subtitle_box">
                  Lorem Ipsum Dolores Sumitas Simitus
                  <br/>Afranio Voluptat Sedio Proin Commodo Aesopio Volutpat Blandit
              </div>
              <div  class="link_box">
                  >
              </div>
          </div>
          <span class="overlay"></span>
      </div>
      <div class="item item_home" style="background-image: url('App/View/Templates/img/bg_box_home.jpg');" >
          <div class="text_box">
              <div class="title_box">
                  Helen Rose
                  <br/>England Striker
              </div>
              <div  class="subtitle_box">
                  Lorem Ipsum Dolores Sumitas Simitus
                  <br/>Afranio Voluptat Sedio Proin Commodo Aesopio Volutpat Blandit
              </div>
              <div  class="link_box">
                  >
              </div>
          </div>
          <span class="overlay"></span>
      </div>
      <div class="item item_home" style="background-image: url('App/View/Templates/img/bg_box_home.jpg');" >
          <div class="text_box">
              <div class="title_box">
                  Helen Rose
                  <br/>England Striker
              </div>
              <div  class="subtitle_box">
                  Lorem Ipsum Dolores Sumitas Simitus
                  <br/>Afranio Voluptat Sedio Proin Commodo Aesopio Volutpat Blandit
              </div>
              <div  class="link_box">
                  >
              </div>
          </div>
          <span class="overlay"></span>
      </div>
      <div class="item item_home" style="background-image: url('App/View/Templates/img/bg_box_home.jpg');" >
          <div class="text_box">
              <div class="title_box">
                  Helen Rose
                  <br/>England Striker
              </div>
              <div  class="subtitle_box">
                  Lorem Ipsum Dolores Sumitas Simitus
                  <br/>Afranio Voluptat Sedio Proin Commodo Aesopio Volutpat Blandit
              </div>
              <div  class="link_box">
                  >
              </div>
          </div>
          <span class="overlay"></span>
      </div>
      <div class="item item_home" style="background-image: url('App/View/Templates/img/bg_box_home.jpg');" >
          <div class="text_box">
              <div class="title_box">
                  Helen Rose
                  <br/>England Striker
              </div>
              <div  class="subtitle_box">
                  Lorem Ipsum Dolores Sumitas Simitus
                  <br/>Afranio Voluptat Sedio Proin Commodo Aesopio Volutpat Blandit
              </div>
              <div  class="link_box">
                  >
              </div>
          </div>
          <span class="overlay"></span>
      </div>

 </div>

<div class="home_sentence">
    <p class="home_sentence_text">“MY GAME SPEED HAS CHANGED DRAMATICALLY SINCE”</p>
    <p class="home_sentence_author">Steven gerrard</p>
    <div class="home_sentence_button">
        <span >VIEW COLLECTION</span>
    </div>
</div>


<div class="bottom_boxes">
    <div class="content">&nbsp;
        </div>

</div>

  <?php include("footer.inc.php");?>

  <!-- JavaScript at the bottom for fast page loading -->



  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>')</script>

  <!-- scripts concatenated and minified via build script -->
  <script src="App/View/Templates/js/plugins.js"></script>
  <script src="App/View/Templates/js/script.js"></script>
  <script src="App/View/Templates/js/libs/jquery.masonry.min.js"></script>

  <script src="App/View/Templates/js/jquery.flexslider.js"></script>
  <script>
  	$(function(){
  		$('#container').masonry({
    // options
    itemSelector : '.item'
    
  	});
  });

    $('.flexslider').flexslider();
  </script>

  <!-- end scripts -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-22756494-1'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
</body>
</html>