<?php include("header.inc.php");?>

<body>
  <?php echo include("cap.inc.php");?>
  <div id="imagetop">
        <img src="App/View/Templates/img/wear.jpg"/>
        <h1 class="header_banner">WEAR</h1>
  </div>

  <div class="row_tip">
      <div class="row_tip_center">
          <p class="wear_tip">Your step-by-step guide to wearing Trusox products</p>
      </div>

  </div>






<div class="row_content">
    <div class="row_content_center">
        <iframe width="930" height="523" src="//www.youtube.com/embed/T-hWSjjZ4hY" frameborder="0" allowfullscreen></iframe>

    </div>

</div>

  <div class="row_content">


      <div class="row_content_center">
          <div class="content3cols_box">
              <p class="box_title1">Mid Half Sock</p>
              <span class="box_watch">Watch</span>
              <img src="App/View/Templates/img/wear_box.jpg" />
          </div>
          <div class="content3cols_box">
              <p class="box_title1">Mid Half Sock</p>
              <span class="box_watch">Watch</span>
              <img src="App/View/Templates/img/wear_box.jpg" />
          </div>
          <div class="content3cols_box">
              <p class="box_title1">Mid Half Sock</p>
              <span class="box_watch">Watch</span>
              <img src="App/View/Templates/img/wear_box.jpg" />
          </div>
      </div>

  <div class="footer">


      <div class="content">
          <div class="footer_box">
               <p class="footer_title">TRUSOX</p>
               <hr class="footer_title_separator"/>
               <ul class="footer_links">
                  <li>HOW TO WEAR IT<li></li>
                  <li>THE SHOP</li>
                  <li>STORE LOCATOR</li>
                  <li>CONTACT US</li>
               </ul>
               <ul class="footer_links">
                  <li>HOW TO WEAR IT<li></li>
                  <li>THE SHOP</li>
                  <li>STORE LOCATOR</li>
                  <li>CONTACT US</li>
               </ul>

          </div>
          <div class="footer_box">
              <p class="footer_title">TRUSOX IN SPORT</p>
              <hr class="footer_title_separator"/>
              <ul class="footer_links">
                  <li>FOOTBALL</li>
                  <li>CRICKET</li>
                  <li>TENNIS</li>
                  <li>GOLF</li>
              </ul>
              <ul class="footer_links">
                  <li>RUNNING</li>
                  <li>BADMINTON</li>
                  <li>BOXING</li>
                  <li>BASKETBALL</li>
              </ul>

          </div>
          <div class="footer_box">
              <p class="footer_title">SOCIAL</p>
              <hr class="footer_title_separator"/>
              <ul class="footer_links">
                  <li>FACEBOOK<li></li>
                  <li>TWITER</li>

              </ul>
              <ul class="footer_links">
                  <li>INSTAGRAM<li></li>
                  <li>YOUTUBE</li>

              </ul>
          </div>
      </div>



      <div class="footer_logo_content">
          <div class="footer_logo_content_center">
              <a href="index.php" class="footer_logo">Trusox</a>

          </div>
      </div>


      <div class="credits">
          <div class="credits_center">© 2013 TRUSOX All Rights Reserved</div>

      </div>



  </div>


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.1.min.js"><\/script>')</script>

  <!-- scripts concatenated and minified via build script -->
  <script src="App/View/Templates/js/plugins.js"></script>
  <script src="App/View/Templates/js/script.js"></script>
  <script src="App/View/Templates/js/libs/jquery.masonry.min.js"></script>
  <script>
  	$(function(){
  		$('#container').masonry({
    // options
    itemSelector : '.item'
    
  	});
  });
  </script>
  <!-- end scripts -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script>
    var _gaq=[['_setAccount','UA-22756494-1'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
</body>
</html>